move build step into separate job
This separates out the steps to build the tarball used for deployments
into its own job, making it no longer dependent on the unit tests
completing before the updated tarball can be deployed according to the
rules defined in the repository's `SOURCE_TARGET_MAP` JSON variable.
This will allow deployments to be made without waiting for 2 full rounds
of unit tests to complete, as is currently the case.

However, the current branch protection rules do not ensure that the unit
tests required by a PR were run on the same code that will be deployed
if the PR is merged. This is because the unit tests are run on the head
branch of the PR, while the deployment is made from the merged result of
the PR. When the 2 full tests were being run, this was not an issue
because the 2nd test run was done on the merged result of the PR, and
the deploy job would wait for that 2nd test run to succeed.

To recoup the protection of the 2nd test run while keeping the speed
gained by breaking out these steps, another branch protection rule must
be added to the repo requiring the head branch of a PR to be fully
updated with the base branch of the PR. This will ensure all tests which
were run on the head branch will correctly reflect how they will run on
the merged result of the PR. This will also ensure that the deployment
will be made from the same code that was tested.

The only negative to adding this rule is that it will require all PRs
merging changes up the chain of `develop` to `staging` to `master` to be
done using proxy branches, since those branches cannot be updated with
the base branch of the PR directly due to branch protection rules.

This also performs a few cleanup items on the workflow file and related
scripts.

diff --git a/.github/workflows/build-middleware.yml b/.github/workflows/build-middleware.yml
--- a/.github/workflows/build-middleware.yml
+++ b/.github/workflows/build-middleware.yml
@@ -27,26 +27,30 @@ env:
     }
     export -f export
 jobs:
-  build:
-    name: Build, Run Tests, Store Artifacts
+  prep:
     runs-on: ubuntu-latest
     outputs:
+      debugFlag: ${{ steps.setBuildVars.outputs.debugFlag }}
       branchName: ${{ steps.setBuildVars.outputs.branchName }}
+      sanitizedBranchName: ${{ steps.setBuildVars.outputs.sanitizedBranchName }}
       micronautEnv: ${{ steps.setBuildVars.outputs.micronautEnv }}
       releaseEnvironment: ${{ steps.setBuildVars.outputs.releaseEnvironment }}
       deployTargets: ${{ steps.setBuildVars.outputs.deployTargets }}
-      tarball: ${{ steps.buildDeployArtifact.outputs.deployFile }}
+      networkId: ${{ steps.setBuildVars.outputs.networkId }}
+      jenkinsUid: ${{ steps.setBuildVars.outputs.jenkinsUid }}
+      jenkinsGid: ${{ steps.setBuildVars.outputs.jenkinsGid }}
+      fastfail: ${{ steps.setBuildVars.outputs.fastfail }}
+      releaseVersion: ${{ steps.setBuildVars.outputs.releaseVersion }}
+      etagsJson: ${{ steps.validateBranchName.outputs.etagsJson }}
+      branchFolder: ${{ steps.validateBranchName.outputs.branchFolder }}
+      validBranchName: ${{ steps.validateBranchName.outputs.validBranchName }}
+      baseBranchName: ${{ steps.validateBranchName.outputs.baseBranchName }}
+      branchCoreName: ${{ steps.validateBranchName.outputs.branchCoreName }}
     steps:
     - name: Check out code
       uses: actions/checkout@v4
       with:
         show-progress: false
-
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-       java-version: '11'
-       distribution: 'temurin'
 
     - name: Set build variables
       id: setBuildVars
@@ -58,20 +62,51 @@ jobs:
       run: ${{ github.workspace }}/.github/workflows/scripts/set-build-variables.py
 
     - name: Validate branch name
+      id: validateBranchName
       env:
-        DEBUG_MODE: ${{ steps.setBuildVars.outputs.debugMode == 'true' && 'set -x' || '' }}
+        DEBUG_MODE: ${{ steps.setBuildVars.outputs.debugFlag == 'true' && 'set -x' || '' }}
         BRANCH_NAME: ${{ steps.setBuildVars.outputs.branchName }}
+        DUMPFILES_ETAGS_JSON: ${{ vars.DUMPFILES_ETAGS_JSON }}
       run: |
+        #!/usr/bin/env bash
         ${DEBUG_MODE}
+
+        #the branch name is used in a docker tag, so it must be a valid docker tag, and under 50 characters
         if [ ${#BRANCH_NAME} -gt 50 ]; then
-          echo "Branch name is too long: ${BRANCH_NAME} (${#BRANCH_NAME} characters). Maximum length is 50 characters."
+          echo "::error:: Branch name is too long: ${BRANCH_NAME} (${#BRANCH_NAME} characters). Maximum length is 50 characters."
+          exit 1
+        fi
+        if [[ ! "${BRANCH_NAME}" =~ ^[a-zA-Z0-9][a-zA-Z0-9_./-]+$ ]]; then
+          echo "::error:: Invalid branch name: ${BRANCH_NAME}"
           exit 1
         fi
 
+        ${{ env.BASH_EXPORT_OVERRIDE }}
+        source ${GITHUB_WORKSPACE}/.github/workflows/scripts/validate-branch-name.sh \
+          || : # ignore failed validation, use the results anyway
+        {
+          echo "validBranchName=${VALID_BRANCH_NAME}"
+          echo "branchFolder=${BRANCH_FOLDER}"
+          echo "baseBranchName=${BASE_BRANCH_NAME}"
+          echo "branchCoreName=${BRANCH_CORE_NAME}"
+        } >> "${GITHUB_OUTPUT}"
+
+        #this will fully escape the double quotes in the embedded JSON string
+        echo "etagsJson=${DUMPFILES_ETAGS_JSON//\"/\\\"}" >> "${GITHUB_OUTPUT}"
+
+  unitTesting:
+    needs: prep
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check out code
+      uses: actions/checkout@v4
+      with:
+        show-progress: false
+
     - name: Setup Docker
       env:
-        DEBUG_MODE: ${{ steps.setBuildVars.outputs.debugMode == 'true' && 'set -x' || '' }}
-        NETWORK_ID: ${{ steps.setBuildVars.outputs.networkId }}
+        DEBUG_MODE: ${{ needs.prep.outputs.debugFlag == 'true' && 'set -x' || '' }}
+        NETWORK_ID: ${{ needs.prep.outputs.networkId }}
       run: |
         ${DEBUG_MODE}
         docker network create "$NETWORK_ID"
@@ -79,12 +114,12 @@ jobs:
 
     - name: Test
       env:
-        DEBUG_MODE: ${{ steps.setBuildVars.outputs.debugMode == 'true' && 'set -x' || '' }}
-        BRANCH_NAME: ${{ steps.setBuildVars.outputs.branchName }}
-        JENKINS_UID: ${{ steps.setBuildVars.outputs.jenkinsUid }}
-        JENKINS_GID: ${{ steps.setBuildVars.outputs.jenkinsGid }}
-        NETWORK_ID: ${{ steps.setBuildVars.outputs.networkId }}
-        FASTFAIL: ${{ steps.setBuildVars.outputs.fastfail == 'true' && '--fail-fast' || '' }}
+        DEBUG_MODE: ${{ needs.prep.outputs.debugFlag == 'true' && 'set -x' || '' }}
+        BRANCH_NAME: ${{ needs.prep.outputs.sanitizedBranchName }}
+        JENKINS_UID: ${{ needs.prep.outputs.jenkinsUid }}
+        JENKINS_GID: ${{ needs.prep.outputs.jenkinsGid }}
+        NETWORK_ID: ${{ needs.prep.outputs.networkId }}
+        FASTFAIL: ${{ needs.prep.outputs.fastfail == 'true' && '--fail-fast' || '' }}
       run: |
         ${DEBUG_MODE}
         echo "::group::docker build cynergibasedb"
@@ -129,24 +164,71 @@ jobs:
         "
         echo "::endgroup::"
 
-    - name: Build deploy artifact
-      id: buildDeployArtifact
-      if: ${{ (success() || failure()) && steps.setBuildVars.outputs.releaseEnvironment != '' }}
+    - name: Prepare unit tests report
+      id: prepareUnitTestsReport
+      if: ${{ success() || failure() }}
+      continue-on-error: true
       env:
-        DEBUG_MODE: ${{ steps.setBuildVars.outputs.debugMode == 'true' && 'set -x' || '' }}
-        BRANCH_NAME: ${{ steps.setBuildVars.outputs.branchName }}
-        JENKINS_UID: ${{ steps.setBuildVars.outputs.jenkinsUid }}
-        JENKINS_GID: ${{ steps.setBuildVars.outputs.jenkinsGid }}
-        RELEASE_VERSION: ${{ steps.setBuildVars.outputs.releaseVersion  }}
-        MICRONAUT_ENV: ${{ steps.setBuildVars.outputs.micronautEnv  }}
+        DEBUG_MODE: ${{ needs.prep.outputs.debugFlag == 'true' && 'set -x' || '' }}
       run: |
         ${DEBUG_MODE}
+        reportsPath="${GITHUB_WORKSPACE}/build/reports"
+        if [ -d "${reportsPath}" ] && [ "$(ls -A "${reportsPath}")" ]; then
+          tar -czf "${reportsPath}/unit-tests-report.tar.gz" "${reportsPath}"/*
+          echo "reportsPath=${reportsPath}/unit-tests-report.tar.gz" >> "${GITHUB_OUTPUT}"
+        else
+          echo "::warning:: Path not found: ${reportsPath}"
+        fi
+
+    - name: "Store reports"
+      if: ${{ (success() || failure()) && steps.prepareUnitTestsReport.outputs.reportsPath != '' }}
+      continue-on-error: true
+      uses: actions/upload-artifact@v3
+      with:
+        name: unitTestsReport
+        path: ${{ steps.prepareUnitTestsReport.outputs.reportsPath }}
+        if-no-files-found: warn
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: ${{ success() || failure() }}
+      continue-on-error: true
+      with:
+       report_paths: 'build/test-results/**/*.xml'
+
+  build:
+    needs: prep
+    runs-on: ubuntu-latest
+    outputs:
+      tarball: ${{ steps.buildDeployArtifact.outputs.deployFile }}
+    if: ${{ needs.prep.outputs.releaseEnvironment != '' }}
+    steps:
+    - name: Check out code
+      uses: actions/checkout@v4
+      with:
+        show-progress: false
+
+    - name: Build deploy artifact
+      id: buildDeployArtifact
+      env:
+        DEBUG_MODE: ${{ needs.prep.outputs.debugFlag == 'true' && 'set -x' || '' }}
+        BRANCH_NAME: ${{ needs.prep.outputs.sanitizedBranchName }}
+        JENKINS_UID: ${{ needs.prep.outputs.jenkinsUid }}
+        JENKINS_GID: ${{ needs.prep.outputs.jenkinsGid }}
+        RELEASE_VERSION: ${{ needs.prep.outputs.releaseVersion  }}
+        MICRONAUT_ENV: ${{ needs.prep.outputs.micronautEnv  }}
+      run: |
+        ${DEBUG_MODE}
+        bashDebugFlag=$( [[ "${DEBUG_MODE}" != '' ]] && echo '-x' || echo '' )
+
+        mkdir --verbose gradleCache gradleWrapper
+
         echo "::group::docker build middlewaretar"
         docker build -t middlewaretar:${BRANCH_NAME} --build-arg USER_ID=${JENKINS_UID} --build-arg GROUP_ID=${JENKINS_GID} --build-arg GROOVY_VER=3.0.9 -f ./support/deployment/cynmid/cynmid.dockerfile ./support/deployment/cynmid
         echo "::endgroup::"
 
         echo "::group::docker run middlewaretar"
-        results=$(docker run --rm -v ${GITHUB_WORKSPACE}/gradleCache:/home/jenkins/caches -v ${GITHUB_WORKSPACE}/gradleWrapper:/home/jenkins/wrapper -v ${GITHUB_WORKSPACE}:/home/jenkins/cynergi-middleware -v ${GITHUB_WORKSPACE}/.github/workflows/scripts:/scripts -e BUILD_VERSION=${RELEASE_VERSION} -e MICRONAUT_ENV=${MICRONAUT_ENV} -e RELEASE_VERSION=${RELEASE_VERSION} middlewaretar:${BRANCH_NAME} /bin/bash -c "/scripts/build-tarball.sh")
+        results=$(docker run --rm -v ${GITHUB_WORKSPACE}/gradleCache:/home/jenkins/caches -v ${GITHUB_WORKSPACE}/gradleWrapper:/home/jenkins/wrapper -v ${GITHUB_WORKSPACE}:/home/jenkins/cynergi-middleware -v ${GITHUB_WORKSPACE}/.github/workflows/scripts:/scripts -e BUILD_VERSION=${RELEASE_VERSION} -e MICRONAUT_ENV=${MICRONAUT_ENV} -e RELEASE_VERSION=${RELEASE_VERSION} middlewaretar:${BRANCH_NAME} /bin/bash ${bashDebugFlag} "/scripts/build-tarball.sh")
 
         echo "${results}" | sed 's/^/::debug::/'
         #filter only the results which set variables as expected
@@ -161,39 +243,8 @@ jobs:
         name: ${{ steps.buildDeployArtifact.outputs.deployFile }}
         path: ${{ steps.buildDeployArtifact.outputs.buildPath }}/${{ steps.buildDeployArtifact.outputs.deployFile }}
 
-    - name: Prepare build reports
-      id: prepareBuildReports
-      if: ${{ success() || failure() }}
-      continue-on-error: true
-      env:
-        DEBUG_MODE: ${{ steps.setBuildVars.outputs.debugMode == 'true' && 'set -x' || '' }}
-      run: |
-        ${DEBUG_MODE}
-        reportsPath="${GITHUB_WORKSPACE}/build/reports"
-        if [ -d "${reportsPath}" ] && [ "$(ls -A "${reportsPath}")" ]; then
-          tar -czf "${reportsPath}/reports.tar.gz" "${reportsPath}"/*
-          echo "reportsPath=${reportsPath}/reports.tar.gz" >> "${GITHUB_OUTPUT}"
-        else
-          echo "::warning ::Path not found: ${reportsPath}"
-        fi
-
-    - name: "Store reports"
-      if: ${{ (success() || failure()) && steps.prepareBuildReports.outputs.reportsPath != '' }}
-      continue-on-error: true
-      uses: actions/upload-artifact@v3
-      with:
-        name: buildReports
-        path: ${{ steps.prepareBuildReports.outputs.reportsPath }}
-        if-no-files-found: warn
-
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: ${{ success() || failure() }}
-      continue-on-error: true
-      with:
-       report_paths: 'build/test-results/**/*.xml'
-
   e2eTesting:
+    needs: prep
     runs-on: ubuntu-latest
     continue-on-error: true
     permissions:
@@ -201,44 +252,22 @@ jobs:
       id-token: write
       actions: write
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          show-progress: false
-      - name: Calculate variables
-        id: calcVars
-        env:
-          DUMPFILES_ETAGS_JSON: ${{ vars.DUMPFILES_ETAGS_JSON }}
-        run: |
-          #!/usr/bin/env bash
-          ${{ env.BASH_EXPORT_OVERRIDE }}
-
-          DEBUG_FLAG='false'
-          if [[ '${{ (inputs.debugLogs == true || runner.debug == '1' || vars.ACTIONS_STEP_DEBUG == 'true') && 'true' || 'false' }}' == 'true' ]]; then
-            DEBUG_FLAG='true'
-            set -x
-          fi
-          export DEBUG_FLAG
-
-          BRANCH_NAME='${{ github.ref_name }}'
-          source ${{ github.workspace }}/.github/workflows/scripts/validate-branch-name || exit 0 # ignore failed validation, use the results anyway
-
-          echo "ETAGS_JSON=${DUMPFILES_ETAGS_JSON//\"/\\\"}" >> "${GITHUB_ENV}"
-
       - name: Trigger E2E testing
         uses: hightouchinc/dynamic-uses@v1
         with:
-          uses: hightouchinc/cynergi-e2e/.github/actions/test-e2e@${{ env.BASE_BRANCH_NAME }}
-          with: '{"e2eBranch": "${{ env.BASE_BRANCH_NAME }}", "token": "${{ secrets.READONLY_HTI_PAT }}", "middlewareBranch": "${{ github.ref_name}}", "middlewareSha": "${{ github.sha }}", "clientBranch": "${{ env.BASE_BRANCH_NAME }}", "teamsNotificationWebhook": "${{ secrets.TEAMS_NOTIFICATION_WEBHOOK }}", "dumpfilesEtagsJson": "${{ env.ETAGS_JSON }}", "debugMode": "${{ env.DEBUG_FLAG }}"}'
+          uses: hightouchinc/cynergi-e2e/.github/actions/test-e2e@${{ needs.prep.outputs.baseBranchName }}
+          with: '{"e2eBranch": "${{ needs.prep.outputs.baseBranchName }}", "token": "${{ secrets.READONLY_HTI_PAT }}", "middlewareBranch": "${{ github.ref_name}}", "middlewareSha": "${{ github.sha }}", "clientBranch": "${{ needs.prep.outputs.baseBranchName }}", "teamsNotificationWebhook": "${{ secrets.TEAMS_NOTIFICATION_WEBHOOK }}", "dumpfilesEtagsJson": "${{ needs.prep.outputs.etagsJson }}", "debugMode": "${{ needs.prep.outputs.debugFlag }}"}'
 
   deploy:
-    needs: build
+    needs:
+      - prep
+      - build
     name: Deploy tarball to Gold Box
-    if: ${{ needs.build.outputs.releaseEnvironment != '' }}
+    if: ${{ needs.prep.outputs.deployTargets != '' }}
     uses: ./.github/workflows/deploy-tarball.yml
     with:
       tarball: ${{ needs.build.outputs.tarball }}
       targetDeployable: 'cynergi-middleware-current.tar.xz'
-      releaseEnvironment: ${{ needs.build.outputs.releaseEnvironment }}
-      deployTargets: ${{ needs.build.outputs.deployTargets }}
+      releaseEnvironment: ${{ needs.prep.outputs.releaseEnvironment }}
+      deployTargets: ${{ needs.prep.outputs.deployTargets }}
     secrets: inherit
