add branch name validation workflow

diff --git a/.github/workflows/build-middleware.yml b/.github/workflows/build-middleware.yml
--- a/.github/workflows/build-middleware.yml
+++ b/.github/workflows/build-middleware.yml
@@ -13,6 +13,19 @@ on:
             type: boolean
             default: false
    push:
+env:
+   BASH_EXPORT_OVERRIDE: |
+      # override the export builtin
+      function export() {
+         builtin export "${@?}"
+         [[ "$1" =~ ^- ]] && return 0
+         if [[ "$1" =~ = ]]; then
+            echo "$1" >> "$GITHUB_ENV"
+         else
+            echo "$1=${!1}" >> "$GITHUB_ENV"
+         fi
+      }
+      export -f export
 jobs:
    build:
       name: Build, Run Tests, Store Artifacts
@@ -192,29 +205,23 @@ jobs:
            id: calcVars
            run: |
             #!/usr/bin/env bash
+            ${{ env.BASH_EXPORT_OVERRIDE }}
 
             DEBUG_FLAG='false'
             if [[ '${{ (inputs.debugLogs == true || runner.debug == '1' || vars.ACTIONS_STEP_DEBUG == 'true') && 'true' || 'false' }}' == 'true' ]]; then
                DEBUG_FLAG='true'
                set -x
             fi
-            echo "DEBUG_FLAG=$DEBUG_FLAG" >> "$GITHUB_ENV"
+            export DEBUG_FLAG
 
-            fullBranchName='${{ github.ref_name }}'
-            prefix=${fullBranchName%%.*}
+            BRANCH_NAME='${{ github.ref_name }}'
+            source ${{ github.workspace }}/.github/workflows/scripts/validate-branch-name || exit 0 # ignore failed validation, use the results anyway
 
-            BASE_BRANCH=$fullBranchName
-            #determine if the prefix is a valid git branch of this repository, possibly remote
-            if [[ -n "$(git branch --list --remotes "$prefix" "origin/$prefix")" ]]; then
-               BASE_BRANCH=$prefix
-            fi
-
-            echo "BASE_BRANCH=$BASE_BRANCH" >> "$GITHUB_ENV"
          - name: Trigger E2E testing
            uses: hightouchinc/dynamic-uses@v1
            with:
-            uses: hightouchinc/cynergi-e2e/.github/actions/test-e2e@${{ env.BASE_BRANCH }}
-            with: '{"e2eBranch": "${{ env.BASE_BRANCH }}", "token": "${{ secrets.READONLY_HTI_PAT }}", "middlewareBranch": "${{ github.ref_name}}", "middlewareSha": "${{ github.sha }}", "clientBranch": "${{ env.BASE_BRANCH }}", "teamsNotificationWebhook": "${{ secrets.TEAMS_NOTIFICATION_WEBHOOK }}", "debugMode": "${{ env.DEBUG_FLAG }}"}'
+            uses: hightouchinc/cynergi-e2e/.github/actions/test-e2e@${{ env.BASE_BRANCH_NAME }}
+            with: '{"e2eBranch": "${{ env.BASE_BRANCH_NAME }}", "token": "${{ secrets.READONLY_HTI_PAT }}", "middlewareBranch": "${{ github.ref_name}}", "middlewareSha": "${{ github.sha }}", "clientBranch": "${{ env.BASE_BRANCH_NAME }}", "teamsNotificationWebhook": "${{ secrets.TEAMS_NOTIFICATION_WEBHOOK }}", "debugMode": "${{ env.DEBUG_FLAG }}"}'
 
    deploy:
       needs: build
